version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running unit tests"
      - pytest tests/

  build:
    commands:
      - echo "Starting SageMaker training job"
      - python3 pipeline/run_training.py

artifacts:
  files:
    - '**/*'

